Map<String, String> loLA = {
  'change_theme': 'ປ່ຽນຕິມ',
  'change_language': 'ປ່ຽນພາສາ',
  'language': 'ພາສາ',
  'setting': 'ຕັ້ງຄ່າ',
  'dark_mode': 'ໂໝດມືດ',
  'username': 'ຊື່ຜູ້ໃຊ້',
  'password': 'ລະຫັດຜ່ານ',
  'login': 'ເຂົ້າໃຊ້ລະບົບ',
  'not_login': 'ເຂົ້າໃຊ້ລະບົບ',
  'fail': 'ຂໍຜິດພາດ',
  'error_message': 'ມີຂໍຜິດພາດກະລຸນາລອງໃຫມ່',
  'load_data_from_server': 'ໂຫຼດຂໍ້ມູນຈາກເຊີເວີ',
  'async_last': 'ອັບເດດຂໍ້ມູນລ້າສຸດ',
  'async_data': 'ອັບເດດຂໍ້ມູນ',
  'please_value': 'ກະລຸນາປ້ອນຂໍ້ມູນ',
  'save': 'ບັນທຶກ',
  'cancel': 'ຍົກເລີກ',
  'exit': 'ອອກ',
  'discard': 'ອອກໂດຍບໍ່ບັນທຶກ !',
  'saved': 'ບັນທຶກແລ້ວ !',
  "confirm": "ຢືນຢັນ",
  "option": "ທາງເລືອກ",
  "open_web": "ເປິດເວັບ ແອັດມິນ",
  "select_category": "ເລຶອກຫມວດໝູ່",
  "month": "ເດືອນ",
  "money_num": "ຈໍານວນເງິນ",
  "date": "ວັນທີ",
  "exit_page": "ອອກຈາກ ໜ້າ ນີ້",
  "is_offline": "ກະລຸນາເຊື່ອມຕໍ່ ອິນເທີເນັດ",
  "detail": "ລາຍລະອຽດ",
  "select": "ເລືອກ",
  "cancel_edit": "ຍົກເລີກການແກ້ໄຂຂໍ້ມູນ",
  "select_date": "ເລືອກວັນທີ",
  "id": "ລະຫັດ",
  "mem_date": "ວັນທີເຂົ້າເປັນສະມາຊີກ ",
  "create_date": "ວັນທີສ້າງ ",
  "color": "ສີ ",
  "no_data": "ບໍ່ມີຂໍ້ມູນ",
  "no": "ບໍ່",
  "add_new": "ເພີ່ມໃຫມ່",
  "button_click_new_list": "ຄິຣກປຸ່ມ ທາງລຸ່ມເລີ່ມຕົ້ນ ສ້າງລາຍການໃຫມ່ !",
  "Skip": "ຂ້າມ ",
  "Done": "ສໍາເລັດ ",
  "please_wait": "ກະລຸນາລໍຖ້າ ....",
  "please_val": "ກະລຸນາປ້ອນຂໍ້ມູນ",
  "delete_data": "ລຶບຂໍ້ມູນ",
  "deleted": "ລຶບຂໍ້ມູນແລ້ວ",
  "edit": "ແກ້ໄຂ",
  "search": "ຄົ້ນຫາ",
  "money_total": "ຈໍານວນເງິນ",
  "no_id": "ລໍາລັບ",
  "ok": "ຕົກລົງ",
  "success": "ສໍາເລັດ",
  "restore": "ເລີ້ມຕົ້ນໃຊ້ງານໃຫມ່",
  "async": "ດຶງຂໍ້ມູນ",
  "async_data_success": "ດຶງຂໍ້ມູນສໍາເລັດ",
  "async_success": "ອັບເດດຂໍ້ມູນສໍາເລັດ",
  "password_fail": "ລະຫັດບໍ່ຖືກຕ້ອງ",
  "remember_me": "ຈື່ຂ້ອຍໄວ້",
  "sign_in": "ເຂົ້າສູ່ລະບົບ",
  "add": "ເພີ້ມ",
  "about": "ກ່ຽວກັບ",
  "dark": "ມືດຄື້ມ",
  "delete": "ລຶບ",
  "la": "ພາສາ ລາວ",
  "logout": "ອອກຈາກລະບົບ",
  "en": "English",
  "opening": "ເປີດຢູ່",
  "opened": "ເປີດແລ້ວ",
  "closed": "ປິດແລ້ວ",
  "close": "ປິດ",
  "open": "ເປີດ",
  "total": "ລວມ",
  "close_account": "ປິດບັນຊີ",
  "email": "ອີເມລ",
  "langauge": "ພາສາ",
  "dashboard": "ໜ້າຄອບຄຸມ",
  "home": "ໜ້າຫຼັກ",
  "password_incorrect": "ລະຫັດຜ່ານ ບໍ່ຖືກຕ້ອງ",
  "please_enter_email": "ກະລຸນາປ້ອນ ຊື່ຜູ້ໃຊ້ ຫຼື ອີເມລ",
  "please_enter_password": "ກະລຸນາປ້ອນ  ລະຫັດຜ່ານ",
  "updating": "ກໍາລັງອັບເດດ",
  "no_delete": "ບໍ່ລຶບ",
  "notify": "ແຈ້ງເຕືອນ",
  "edited": "ແກ້ໄຂແລ້ວ",
  "added": "ເພີ້ມແລ້ວ ",
  "login_with": "ເຂົ້າສູ່ລະບົບ ດ້ວຍ",
  "login_with_pass": "ເຂົ້າສູ່ລະບົບ ດ້ວຍ ລະຫັດຜ່ານ",
};
